#!/bin/bash

# Copyright (C) 2007, 2008, 2009 Google Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

# Modified by Stephen Fromm <stephenf nero net>
# (C) 2012 University of Oregon

set -e

. common.sh

TMPDIR=`mktemp -d` || exit 1
CLEANUP+=("rmdir $TMPDIR")

# Make sure we have enough information to proceed
check_cobbler_auth_args

# If the target device is not a real block device we'll first losetup it.
# This is needed for file disks.
if [ ! -b $blockdev ]; then
  ORIGINAL_BLOCKDEV=$blockdev
  blockdev=$(losetup -sf $blockdev)
  CLEANUP+=("losetup -d $blockdev")
fi

if [ "$PARTITION_STYLE" = "none" ]; then
  filesystem_dev=$blockdev
elif [ "$PARTITION_STYLE" = "msdos" ]; then
  filesystem_dev=$(map_disk0 $blockdev)
  CLEANUP+=("unmap_disk0 $blockdev")
else
  echo "Unknown partition style $PARTITION_STYLE"
  exit 1
fi

mount $filesystem_dev $TMPDIR
CLEANUP+=("umount $TMPDIR")


if [ -e $TMPDIR/etc/hostname ]; then
    HNAME="$TMPDIR/etc/hostname"
    OLD_HNAME="$(cat HNAME)"
elif [ -e $TMPDIR/etc/sysconfig/network ]; then
    HNAME="${TARGET}/etc/sysconfig/network"
    OLD_HNAME="$(grep HOSTNAME ${HNAME} | \
        sed -e 's/HOSTNAME=//' | \
        sed -e s/\"//g)"
elif [ -f $TMPDIR/etc/HOSTNAME ]; then
    HNAME="${TARGET}/etc/HOSTNAME"
    OLD_HNAME="$(cat $HNAME)"
else
    log_error "Cannot determine OS type"
    exit 1
fi

if [ "$OLD_HNAME" = "$old_name" \
        -o "${OLD_HNAME}.$(echo $old_name | cut -d . -f 2,3)" \
        = "$old_name" ] ; then
    if [ -e $TMPDIR/etc/hostname -o $TMPDIR/etc/HOSTNAME ]; then
        echo $instance > $HNAME
    elif [ -e $TMPDIR/etc/sysconfig/network ]; then
        sed -ie "s/HOSTNAME=${OLD_HNAME}/HOSTNAME=${instance}/" $HNAME
    fi

    ./gnt-cobbler.py -x rename --server $COBBLER_SERVER \
                               --username $COBBLER_USER \
                               --password $COBBLER_PASS \
                               --hostname $old_name \
                               --newname $instance
    if [ $? -ne 0 ]; then
        log_error "Call to cobbler failed to rename $old_name to $instance"
        exit 1
    fi
else
    log_error "Cannot rename from $old_name to $instance:"
    log_error "Instance has a different hostname ($OLD_HNAME)"
    exit 1
fi

# execute cleanups
cleanup
trap - EXIT

exit 0
